/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gmail_benrcarver_distributed_DistributedFileSystem */

#ifndef _Included_com_gmail_benrcarver_distributed_DistributedFileSystem
#define _Included_com_gmail_benrcarver_distributed_DistributedFileSystem
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    initNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_initNative
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    disposeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_disposeNative
  (JNIEnv *, jobject, jlong);

  /*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    resetNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_resetNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    readNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_readNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    writeNative
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_writeNative
  (JNIEnv *, jobject, jlong, jstring, jstring, jint);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    mkdirNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_mkdirNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    createFileNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_createFileNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    lsNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_lsNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    getStatFileNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_getStatFileNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    getStatDirNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_getStatDirNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    openNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_openNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    closeNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_closeNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    renameNative
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_renameNative
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    deleteFileNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_deleteFileNative
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    createRootNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_createRootNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    createFileWithDataNative
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_createFileWithDataNative
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    getTotalLatencyNative
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_getTotalLatencyNative
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    getTotalLatencySquaredNative
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_getTotalLatencySquaredNative
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif