/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_gmail_benrcarver_distributed_DistributedFileSystem.h"
#include "client.hpp"
/* Header for class com_gmail_benrcarver_distributed_DistributedFileSystem */

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    initNative
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_initNative(JNIEnv *env, jobject obj, jstring jZookeeperHost)
{
  const char *rawZookeeperHost = env->GetStringUTFChars(jZookeeperHost, nullptr);
  if (rawZookeeperHost == nullptr)
  {
    return reinterpret_cast<jint>(-1);
  }

  std::string zkHost(rawZookeeperHost);
  env->ReleaseStringUTFChars(jZookeeperHost, rawZookeeperHost);

  Client *instance = new Client(zkHost);
  return reinterpret_cast<jlong>(instance);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    disposeNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_disposeNative(JNIEnv *, jobject, jlong jHandle)
{
  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    delete client;
  }
  
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    resetNative
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_resetNative(JNIEnv *, jobject, jlong jHandle)
{
  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    client->reset_latencies();
  }
  
}
/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    readNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_readNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jFilePath)
{
  const char *rawFilePath = env->GetStringUTFChars(jFilePath, nullptr);
  if (rawFilePath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string filePath(rawFilePath);
  env->ReleaseStringUTFChars(jFilePath, rawFilePath);

  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->direct_read(filePath, 4000));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    writeNative
 * Signature: (JLjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_writeNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jFilePath, jstring jBuffer, jint jPosition)
{
  const char *rawFilePath = env->GetStringUTFChars(jFilePath, nullptr);
  if (rawFilePath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string filePath(rawFilePath);
  env->ReleaseStringUTFChars(jFilePath, rawFilePath);

  const char *rawBuffer = env->GetStringUTFChars(jBuffer, nullptr);
  if (rawBuffer == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string buffer(rawBuffer);
  env->ReleaseStringUTFChars(jBuffer, rawBuffer);

  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->write(filePath, buffer, static_cast<uint32_t>(jPosition)));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    mkdirNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_mkdirNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jDirectory)
{
  const char *rawDirectory = env->GetStringUTFChars(jDirectory, nullptr);
  if (rawDirectory == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string directory(rawDirectory);
  env->ReleaseStringUTFChars(jDirectory, rawDirectory);
  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->mkdir(directory));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    createFileNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_createFileNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jFilePath)
{
  const char *rawFilePath = env->GetStringUTFChars(jFilePath, nullptr);
  if (rawFilePath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string filePath(rawFilePath);
  env->ReleaseStringUTFChars(jFilePath, rawFilePath);

  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->add_file(filePath));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    deleteFileNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_deleteFileNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jFilePath)
{
  const char *rawFilePath = env->GetStringUTFChars(jFilePath, nullptr);
  if (rawFilePath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string filePath(rawFilePath);
  env->ReleaseStringUTFChars(jFilePath, rawFilePath);

  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->delete_file(filePath));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    lsNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_lsNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jPath)
{
  const char *rawPath = env->GetStringUTFChars(jPath, nullptr);
  if (rawPath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string path(rawPath);
  env->ReleaseStringUTFChars(jPath, rawPath);

  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->ls(path));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    getStatFileNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_getStatFileNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jPath)
{
  const char *rawPath = env->GetStringUTFChars(jPath, nullptr);
  if (rawPath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string path(rawPath);
  env->ReleaseStringUTFChars(jPath, rawPath);

  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->get_stat_file(path));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    getStatDirNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_getStatDirNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jPath)
{
  const char *rawPath = env->GetStringUTFChars(jPath, nullptr);
  if (rawPath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string path(rawPath);
  env->ReleaseStringUTFChars(jPath, rawPath);

  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->get_stat_dir(path));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    openNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_openNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jPath)
{
  const char *rawFilePath = env->GetStringUTFChars(jPath, nullptr);
  if (rawFilePath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string filePath(rawFilePath);
  env->ReleaseStringUTFChars(jPath, rawFilePath);

  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->open_file(filePath));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    closeNative
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_closeNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jPath)
{
  const char *rawFilePath = env->GetStringUTFChars(jPath, nullptr);
  if (rawFilePath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string filePath(rawFilePath);
  env->ReleaseStringUTFChars(jPath, rawFilePath);

  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->close_file(filePath));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    renameNative
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_renameNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jPath, jstring jNewPath)
{
  const char *rawFilePath = env->GetStringUTFChars(jPath, nullptr);
  if (rawFilePath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string filePath(rawFilePath);
  env->ReleaseStringUTFChars(jPath, rawFilePath);

  const char *rawNewFilePath = env->GetStringUTFChars(jNewPath, nullptr);
  if (rawNewFilePath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string newFilePath(rawNewFilePath);
  env->ReleaseStringUTFChars(jNewPath, rawNewFilePath);

  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->rename_file(filePath, newFilePath));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    createRootNative
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_createRootNative(JNIEnv *env, jobject obj, jlong jHandle)
{
  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->init("/"));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    createFileWithDataNative
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_createFileWithDataNative(JNIEnv *env, jobject obj, jlong jHandle, jstring jFilePath, jstring jBuffer)
{
  const char *rawFilePath = env->GetStringUTFChars(jFilePath, nullptr);
  if (rawFilePath == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string filePath(rawFilePath);
  env->ReleaseStringUTFChars(jFilePath, rawFilePath);

  const char *rawBuffer = env->GetStringUTFChars(jBuffer, nullptr);
  if (rawBuffer == nullptr)
    return reinterpret_cast<jint>(-1);
  std::string buffer(rawBuffer);
  env->ReleaseStringUTFChars(jBuffer, rawBuffer);

  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return reinterpret_cast<jint>(client->create_and_write_file_single_request(filePath, buffer));
  }
  return reinterpret_cast<jint>(-1);
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    getTotalLatencyNative
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_getTotalLatencyNative(JNIEnv *env, jobject obj, jlong jHandle)
{
  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return static_cast<jdouble>(client->get_total_latency());
  }
  return -1;
}

/*
 * Class:     com_gmail_benrcarver_distributed_DistributedFileSystem
 * Method:    getTotalLatencySquaredNative
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_com_gmail_benrcarver_distributed_DistributedFileSystem_getTotalLatencySquaredNative(JNIEnv *env, jobject obj, jlong jHandle)
{
  Client *client = reinterpret_cast<Client *>(jHandle);
  if (client != nullptr)
  {
    return static_cast<jdouble>(client->get_total_latency_squared());
  }
  return -1;
}